require 'spec_helper'

describe Post do
  context 'creating' do
    it 'lets the user create a post' do
      post = FactoryGirl.build :post
      visit new_post_path
      fill_in 'Name', :with => post.name
      fill_in 'Link', :with => post.link
      click_button 'Create Post'
      page.should have_content post.name
    end
  end

  context 'viewing' do
    it 'lets the user visit the link generated by the post' do
      post = FactoryGirl.create :google
      visit posts_path
      click_link post.name
      page.has_content? 'http://www.google.com'
    end
    it 'lets the user visit the objects show page by clicking view post' do
      post = FactoryGirl.create :google
      visit posts_path
      click_link 'View Post'
      page.has_content? post.name
      page.has_content? post.link
      page.has_content? 'Edit'
      page.has_content? 'Delete'
      page.has_content? 'Homepage'
    end
  end

  context 'editing' do
    it 'can be edited by the user' do
      post = FactoryGirl.create :yahoo
      visit post_path post
      click_link "Edit"
      fill_in 'Name', :with => "Bing"
      click_button 'Update Post'
      page.has_content? "Bing"
      page.has_content? "http://www.yahoo.com"
    end
  end

  context 'deleting' do
    it 'can be deleted by the user' do
      post = FactoryGirl.create :google
      visit post_path post
      click_link 'Delete'
      page.should have_no_content post.name
    end
  end
end
